kind: Service
apiVersion: v1
metadata:
  name: coffee-shop
spec:
  selector:
    app: coffee-shop
  ports:
  - port: 8080
---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: coffee-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-shop
      version: v1
  template:
    metadata:
      labels:
        app: coffee-shop
        version: v1
    spec:
      containers:
      - name: coffee-shop
        image: sdaschner/coffee-shop:quarkus-testing-1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
      restartPolicy: Always
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coffee-shop
spec:
  hosts:
  - coffee-shop
  http:
  - route:
    - destination:
        host: coffee-shop
        subset: v1
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: coffee-shop
spec:
  host: coffee-shop
  subsets:
  - name: v1
    labels:
      version: v1
---
